### ISSUE TITLE
Fix retrieve output from YAML

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/attachment#33]
`bookdown::html_document2` is not correctly retrieved with `att_from_rmd()` ans `code_folding: "show"` may lead to parse problems

````yaml
---
title: "My Title"
author: "Sébastien Rochette"
date: "23/01/2021"
output: 
  bookdown::html_document2:
    toc: true
    code_folding: "show"
editor_options: 
  chunk_output_type: console
---
````
